name: test-slo
channels:
  - conda-forge
dependencies:
  - python==3.11
  - notebook
  - ipykernel
  - openpyxl
  - pip
  - pip:
    - bokeh_sampledata==2024.2
    - git+https://github.com/mahynski/pychemauth@7e9ac38
