name: project-name
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - pre-commit
  - scipy
  - seaborn
  - scikit-learn
  - tqdm
  - watermark
  - pip
  - pip:
    - pacmap
